#!/usr/bin/env python3
"""Build an auditable, self-contained repository release archive."""

from __future__ import annotations

import hashlib
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
GIT_LIMIT_BYTES = 20 * 1024 * 1024

INCLUDE_DIRECTORIES: Sequence[str] = (
    "src",
    "topology",
    "tests",
    "intents",
    "experiments",
    "docs",
    "prompts",
    "tools",
    "docker",
    ".github",
)
INCLUDE_FILES: Sequence[str] = (
    "Dockerfile",
    "docker-compose.yml",
    "requirements.txt",
    "Makefile",
    "README.md",
    "LICENSE",
    "CITATION.cff",
    "demo_st4.py",
    ".gitignore",
    "SETUP.md",
)
EXCLUDED_DIRECTORIES = {
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
}
EXCLUDED_SUFFIXES = (".pyc", ".db", ".db-wal", ".db-shm")


def directory_size(path: Path) -> int:
    """Return the bytes stored in regular files below a directory."""
    return sum(item.stat().st_size for item in path.rglob("*") if item.is_file())


def exclusion_reason(relative: Path) -> str:
    """Return the release exclusion rule matching a file, if any."""
    if any(part in EXCLUDED_DIRECTORIES for part in relative.parts):
        return "cache or virtual-environment directory"
    if relative.name == ".DS_Store":
        return ".DS_Store"
    if relative.name.startswith("~$"):
        return "temporary office file"
    if relative.name.endswith(EXCLUDED_SUFFIXES):
        return "generated bytecode or database"
    if (
        len(relative.parts) >= 3
        and relative.parts[0:2] == ("experiments", "figures")
        and relative.suffix.lower() in {".png", ".pdf"}
    ):
        return "generated experiment figure"
    return ""


def files_below(path: Path, excluded: List[Tuple[str, str]]) -> Iterable[Path]:
    """Walk one included directory while pruning excluded directories."""
    for directory, names, filenames in os.walk(path):
        current = Path(directory)
        kept_names = []
        for name in sorted(names):
            candidate = current / name
            relative = candidate.relative_to(ROOT)
            reason = exclusion_reason(relative)
            if reason:
                excluded.append((relative.as_posix() + "/", reason))
            else:
                kept_names.append(name)
        names[:] = kept_names
        for filename in sorted(filenames):
            candidate = current / filename
            relative = candidate.relative_to(ROOT)
            reason = exclusion_reason(relative)
            if reason:
                excluded.append((relative.as_posix(), reason))
            elif candidate.is_file():
                yield candidate


def discover_exclusions() -> List[Tuple[str, str]]:
    """Inventory excluded artifacts even when they sit outside included roots."""
    excluded: List[Tuple[str, str]] = []
    for directory, names, filenames in os.walk(ROOT):
        current = Path(directory)
        kept_names = []
        for name in sorted(names):
            candidate = current / name
            relative = candidate.relative_to(ROOT)
            if relative.parts and relative.parts[0] == "dist":
                continue
            reason = exclusion_reason(relative)
            if reason:
                excluded.append((relative.as_posix() + "/", reason))
            else:
                kept_names.append(name)
        names[:] = kept_names
        for filename in sorted(filenames):
            candidate = current / filename
            relative = candidate.relative_to(ROOT)
            reason = exclusion_reason(relative)
            if reason:
                excluded.append((relative.as_posix(), reason))
    return excluded


def collect_files(include_git: bool) -> Tuple[List[Path], List[Tuple[str, str]]]:
    """Resolve the release allow-list and record every applied exclusion."""
    included: List[Path] = []
    excluded = discover_exclusions()
    directories = list(INCLUDE_DIRECTORIES)
    if include_git:
        directories.append(".git")

    for name in directories:
        path = ROOT / name
        if path.is_dir():
            included.extend(files_below(path, excluded))
        else:
            excluded.append((name, "requested release path is missing"))

    for name in INCLUDE_FILES:
        path = ROOT / name
        if not path.is_file():
            excluded.append((name, "requested release file is missing"))
            continue
        reason = exclusion_reason(Path(name))
        if reason:
            excluded.append((name, reason))
        else:
            included.append(path)

    unique = {path.relative_to(ROOT).as_posix(): path for path in included}
    return [unique[name] for name in sorted(unique)], sorted(set(excluded))


def zip_info(path: Path, archive_name: str) -> ZipInfo:
    """Create a Unix-compatible member so shell scripts remain executable."""
    info = ZipInfo.from_file(path, arcname=archive_name)
    info.compress_type = ZIP_DEFLATED
    info.create_system = 3
    executable = path.suffix == ".sh"
    permissions = 0o100755 if executable else 0o100644
    info.external_attr = permissions << 16
    return info


def write_zip(destination: Path, files: Iterable[Path]) -> None:
    """Write the selected repository files to a fresh archive."""
    with ZipFile(destination, "w", compression=ZIP_DEFLATED) as archive:
        for path in files:
            name = path.relative_to(ROOT).as_posix()
            with path.open("rb") as source, archive.open(zip_info(path, name), "w") as target:
                shutil.copyfileobj(source, target)


def sha256(path: Path) -> str:
    """Calculate a download-verification digest without loading the zip at once."""
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_manifest(
    archive: Path,
    files: Sequence[Path],
    excluded: Sequence[Tuple[str, str]],
    git_note: str,
) -> str:
    """Write included sizes, exclusions, and the finished archive digest."""
    digest = sha256(archive)
    included_bytes = sum(path.stat().st_size for path in files)
    lines = [
        "Intent-Based SDN release manifest",
        "Generated UTC: " + datetime.now(timezone.utc).isoformat(),
        "Archive: " + archive.name,
        "Git history: " + git_note,
        "Included files: " + str(len(files)),
        "Included bytes: " + str(included_bytes),
        "Excluded entries: " + str(len(excluded)),
        "ZIP SHA-256: " + digest,
        "",
        "INCLUDED FILES",
    ]
    for path in files:
        lines.append(
            "{} | {} bytes".format(
                path.relative_to(ROOT).as_posix(), path.stat().st_size
            )
        )
    lines.extend(["", "EXCLUDED ENTRIES"])
    if excluded:
        lines.extend("{} | {}".format(path, reason) for path, reason in excluded)
    else:
        lines.append("(none)")
    lines.append("")
    (DIST / "MANIFEST.txt").write_text("\n".join(lines), encoding="utf-8")
    return digest


def main() -> int:
    """Build the dated archive and print the complete exclusion audit."""
    DIST.mkdir(exist_ok=True)
    git_path = ROOT / ".git"
    git_bytes = directory_size(git_path) if git_path.is_dir() else 0
    include_git = git_path.is_dir() and git_bytes < GIT_LIMIT_BYTES
    if include_git:
        git_note = "included ({} bytes; below 20 MiB)".format(git_bytes)
    elif git_path.is_dir():
        git_note = (
            "excluded ({} bytes; at least 20 MiB); clone from GitHub for history"
        ).format(git_bytes)
    else:
        git_note = "not present; clone from GitHub for history"

    files, excluded = collect_files(include_git)
    if git_path.is_dir() and not include_git:
        excluded.append((".git/", git_note))
        excluded.sort()

    date_stamp = datetime.now().strftime("%Y%m%d")
    archive = DIST / "intent-sdn-sla_{}.zip".format(date_stamp)
    write_zip(archive, files)
    digest = write_manifest(archive, files, excluded, git_note)

    print("Git history: " + git_note)
    print("Excluded entries:")
    if excluded:
        for path, reason in excluded:
            print("  {} - {}".format(path, reason))
    else:
        print("  (none)")
    print("Created: " + archive.relative_to(ROOT).as_posix())
    print("Manifest: dist/MANIFEST.txt")
    print("Included files: " + str(len(files)))
    print("ZIP SHA-256: " + digest)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
